title: 2048 PickMe Project
description: Documentation for the 2048 game project

# Navigation
nav:
  - title: Home
    url: /
  - title: Functional requirements
    url: /functional
  - title: Additional specification
    url: /additional
  - title: Development
    url: /development
  - title: API
    url: /api

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default 
